steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/image1'
      - '.'
  
  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/image1'
  
  # Additional steps...
  # Add any additional steps you need for your build process, such as deploying the image to a Kubernetes cluster or running tests.
  
images:
  # Specify the Docker image to be pushed to Google Container Registry
  - 'gcr.io/$PROJECT_ID/image1'

 Step 3: Deploy the Docker image to GCE
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'update-container'
      - 'instance-1'
      - '--container-image=gcr.io/project-terraform-test-386209/image1:latest'
      - '--zone=us-central1-c'
      - '--project=project-terraform-test-386209'
